// <auto-generated />
using System;
using LaptopStoreRefactorDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaptopStoreRefactorDb.Migrations
{
    [DbContext(typeof(LaptopStoreRefactor))]
    [Migration("20230803163313_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.Laptop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<Guid>("BrandId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId1");

                    b.ToTable("Laptops");
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.LaptopAndStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LaptopId")
                        .HasColumnType("int");

                    b.Property<Guid>("LaptopId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LaptopId1");

                    b.HasIndex("StoreId1");

                    b.ToTable("LaptopsAndStores");
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.Laptop", b =>
                {
                    b.HasOne("LaptopStoreRefactorDb.Model.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.LaptopAndStore", b =>
                {
                    b.HasOne("LaptopStoreRefactorDb.Model.Laptop", "Laptop")
                        .WithMany("LaptopsAndStores")
                        .HasForeignKey("LaptopId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaptopStoreRefactorDb.Model.Store", "Store")
                        .WithMany("LaptopsAndStores")
                        .HasForeignKey("StoreId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laptop");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.Laptop", b =>
                {
                    b.Navigation("LaptopsAndStores");
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.Store", b =>
                {
                    b.Navigation("LaptopsAndStores");
                });
#pragma warning restore 612, 618
        }
    }
}
