// <auto-generated />
using System;
using LaptopStoreRefactorDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaptopStoreRefactorDb.Migrations
{
    [DbContext(typeof(LaptopStoreRefactor))]
    partial class LaptopStoreRefactorModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.Laptop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Laptops", (string)null);
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.LaptopAndStore", b =>
                {
                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LaptopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("StoreId", "LaptopId");

                    b.HasIndex("LaptopId");

                    b.ToTable("LaptopsAndStores", (string)null);
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.Laptop", b =>
                {
                    b.HasOne("LaptopStoreRefactorDb.Model.Brand", "Brand")
                        .WithMany("Laptops")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.LaptopAndStore", b =>
                {
                    b.HasOne("LaptopStoreRefactorDb.Model.Laptop", "Laptop")
                        .WithMany("LaptopsAndStores")
                        .HasForeignKey("LaptopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaptopStoreRefactorDb.Model.Store", "Store")
                        .WithMany("LaptopsAndStores")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laptop");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.Brand", b =>
                {
                    b.Navigation("Laptops");
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.Laptop", b =>
                {
                    b.Navigation("LaptopsAndStores");
                });

            modelBuilder.Entity("LaptopStoreRefactorDb.Model.Store", b =>
                {
                    b.Navigation("LaptopsAndStores");
                });
#pragma warning restore 612, 618
        }
    }
}
